name: frendz_flutter_icons
description: "A handmade set of icons by frendz."
version: 0.0.2
license: MIT
repository: https://github.com/frendzapp/frendz-flutter-icons
issue_tracker: https://github.com/frendzapp/frendz-flutter-icons/issues

environment:
  sdk: ^3.11.1
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.20
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^6.0.0
  vector_graphics_compiler: ^1.2.0

flutter:
  assets:
    - assets/
